### ISSUE TITLE
Adding New Gripper Problem

### ISSUE THREAD

**Issue by Huangruopeng** [IRVLUTD/isaac_sim_grasping#2] opened 2024-07-20 04:29 UTC
Hi 

Thank you for your work, this repo is great.

Now I trying to add my own robotiq 85 gripper. After generate .usd file.
I meet this problem. 

2024-07-20 04:22:10 [5,013ms] [Error] [omni.physx.plugin] PhysX error: PxRigidDynamic::setGlobalPose: pose is not valid., FILE /buildAgent/work/74336105e89c4a74/source/physx/src/NpRigidDynamic.cpp, LINE 91
2024-07-20 04:22:10 [5,013ms] [Error] [omni.physx.plugin] PhysX error: PxRigidDynamic::setLinearVelocity: velocity is not valid., FILE /buildAgent/work/74336105e89c4a74/source/physx/src/NpRigidDynamic.cpp, LINE 207
2024-07-20 04:22:10 [5,013ms] [Error] [omni.physx.plugin] PhysX error: PxRigidDynamic::setAngularVelocity: velocity is not valid., FILE /buildAgent/work/74336105e89c4a74/source/physx/src/NpRigidDynamic.cpp, LINE 231

I try to set different joint velocity, But still has this problem.

Thank you so much!

**Comment by kninad** [comment] 2024-07-20 18:35
This looks like this is an Isaac Sim gripper import issue. Could you share your URDF for the gripper (along with the meshes etc) so that we can also give a try at our end. Tagging @FelipeCasas!

**Comment by FelipeCasas** [comment] 2024-07-20 18:43
Hello, 

Could you expand more about your problem, did the problem arise when running our standalone with your gripper or does this problem arise when importing the gripper .urdf with the GUI?

Kind Regards

**Comment by Huangruopeng** [comment] 2024-07-20 19:07
Hi,

I try to run this command:

lm-2023@lm2023-XPS-8950:~/.local/share/ov/pkg/isaac-sim-2023.1.0-hotfix.1$ ./python.sh /home/lm-2023/Isaac_Sim/grasping/isaac_sim_grasping/visualize_grasps.py --json_dir=/home/lm-2023/Isaac_Sim/grasping/Dataset/graspit_grasps/robotiq --gripper_dir=/home/lm-2023/Isaac_Sim/grasping/isaac_sim_grasping/grippers --objects_dir=/home/lm-2023/Isaac_Sim/grasping/Dataset/google_objects_usd  --num_w=10 --ub=3 --lb=0 --/log/level=error --/log/fileLogLevel=error --/log/outputStreamLevel=error

And the isaacsim will be launched, but just keep 2 seconds, then it closed, and my gripper robotiq 85 2 fingers can be displayed  in the interface, but just 2 senconds.
![image](https://github.com/user-attachments/assets/6a05c56c-a3e3-4a86-91a2-6ce395b50d7c)

The error info:
![image](https://github.com/user-attachments/assets/fb332a50-1d07-4350-b230-5647d5234be4)

This is my URDF file:
[robotiq_2finger.zip](https://github.com/user-attachments/files/16322065/robotiq_2finger.zip)

I follow this setting to import my urdf:
![image](https://github.com/user-attachments/assets/35bf2633-d22b-43e8-a8d8-2e74339bb5f3)

Because my gripper has 8 dofs, so I just use repo graspit Barrett-025.json file to test it can be run.
![image](https://github.com/user-attachments/assets/2993279e-eb4e-4b59-8d43-d458598f5c5c)
(Maybe the dofs data is not match! causing some errs)


Thank you so much!
Kind Regards!

**Comment by Huangruopeng** [comment] 2024-07-20 19:22
Also, I generated my own json file using graspit using neuralgrasps-dataset-generation repo and noticed that the json file generated using it does not match the format of the json I downloaded  from the dataset folder provided in this repo, are there any modifications I need to make to the json I generated for my robotiq 85 2f gripper?

Thank you so much for your help!

**Comment by FelipeCasas** [comment] 2024-07-20 19:30
I see.., within the managers.py file there are many manager classes, since you are using the visualize grasp standalone you will need to add your gripper information to the dictionaries of that class (V_Manager). Try doing so in the https://github.com/IRVLUTD/isaac_sim_grasping/blob/6395a648574935ccb74aa3dd18eaeb0f36b274ec/managers.py#L817 dictionaries and let me know what happens. 

Thanks for letting us now about this issue! We will most likely change the dictionaries to an external file so they can be easily changed and are not so repetitive.

**Comment by Huangruopeng** [comment] 2024-07-20 19:34
I also modify this part:
![image](https://github.com/user-attachments/assets/cee7b7ad-2998-439a-b961-b94a52b35830)

**Comment by FelipeCasas** [comment] 2024-07-20 19:39
Okay, would you mind sharing your .json file and the managers.py file so we can recreate the errors?

**Comment by Huangruopeng** [comment] 2024-07-20 19:44
.json file
[Barrett-025_mug.json](https://github.com/user-attachments/files/16322131/Barrett-025_mug.json)

managers.py
[managers.zip](https://github.com/user-attachments/files/16322140/managers.zip)

**Comment by kninad** [comment] 2024-07-20 19:48
> Also, I generated my own json file using graspit using neuralgrasps-dataset-generation repo and noticed that the json file generated using it does not match the format of the json I downloaded from the dataset folder provided in this repo, are there any modifications I need to make to the json I generated for my robotiq 85 2f gripper?
> 
> Thank you so much for your help!

I guess the only change would in the grasp pose orientation. For isaac sim grasp poses iirc the grasp pose is a 7D vector: `(posn, quat_wxyz)` where the quaternion is in `wxyz` format whereas for the neuralgrasps-dataset-generation, graspit might save it in `(posn, quat_xyzw)` format. So try changing the graspit pose quaternion to `wxyz` format before applying in isaac sim? Perhaps that should at least give you the gripper in correct orientation.

**Comment by FelipeCasas** [comment] 2024-07-20 19:56
Thanks! I will try to reproduce your error. In the meantime, you can try what @kninad says. Isaac Sim quaternion convention is wxyz.

**Comment by Huangruopeng** [comment] 2024-07-20 21:41
Thank you for your help, just a small point maybe is important for you reproduce. 
My urdf read mesh file the path is based on my own path. Please modify it to your own path.
<?xml version="1.0" ?>




<robot name="robotiq_85_gripper">
  <gazebo>
    <plugin filename="libgazebo_ros_control.so" name="gazebo_ros_control">
      
    </plugin>
  </gazebo>
  <link name="world"/>
  <joint name="world_fixed" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="world"/>
    <child link="robotiq_85_base_link"/>
  </joint>
  <link name="robotiq_85_base_link">
    <visual>
      <geometry>
        <mesh filename="package://robotiq_85_description/meshes/visual/robotiq_85_base_link.dae"/>
      </geometry>
    </visual>
    <collision>
    
   filename = should be change to your path.

Thank you so much!

**Comment by Huangruopeng** [comment] 2024-07-20 22:47
Now I can stable visualize it by deleting collision part in my urdf and generate to my .usd without collisions part ( Because I check your .usd file in this repo other gripper don't have collision)

But Now my gripper can't close and open normally, I guess is dofs parameters is not right, considering my gripper also has mimic joints how should I factor this in, any tips would be really helpful.
Can you give some instruction where I can get the right open and close status dofs data?

Close status:
![image](https://github.com/user-attachments/assets/8f31cd10-fe62-4159-bd5d-334df88209dd)

Open status:
![image](https://github.com/user-attachments/assets/e5ccb354-9437-4606-977a-8811f0c7834f)

**Comment by Huangruopeng** [comment] 2024-07-20 22:52
> > Also, I generated my own json file using graspit using neuralgrasps-dataset-generation repo and noticed that the json file generated using it does not match the format of the json I downloaded from the dataset folder provided in this repo, are there any modifications I need to make to the json I generated for my robotiq 85 2f gripper?
> > Thank you so much for your help!
> 
> I guess the only change would in the grasp pose orientation. For isaac sim grasp poses iirc the grasp pose is a 7D vector: `(posn, quat_wxyz)` where the quaternion is in `wxyz` format whereas for the neuralgrasps-dataset-generation, graspit might save it in `(posn, quat_xyzw)` format. So try changing the graspit pose quaternion to `wxyz` format before applying in isaac sim? Perhaps that should at least give you the gripper in correct orientation.

I noticed there are some other parameters like graspit_dofs, final_dofs and fall time in the graspit_grasps json in your dataset while in my json there is only poses, dofs, quality and contact links (the last two are not in your json) am I doing something wrong/missing something?

Thank you!

**Comment by FelipeCasas** [comment] 2024-07-22 18:34
Hello, I was able to replicate your error. It seems that your gripper .usd is not functioning with the PhysiX software. I would recommend to use Isaac Sim GUI to change the .usd of your gripper to a working version. You can use our gripper .usd's as reference.

![Screenshot from 2024-07-22 13-33-21](https://github.com/user-attachments/assets/a03ac847-1ec4-4846-9884-44241025e2e3)

You should be able to manually change the joint positions through the GUI without generating PhysiX errors. An example is below:
 
![Screenshot from 2024-07-22 13-38-31](https://github.com/user-attachments/assets/08c19706-be8a-4f06-a323-90b9e6e202f6)
![Screenshot from 2024-07-22 13-37-30](https://github.com/user-attachments/assets/c804b951-96e3-41bf-a8cb-59cfea5e11b1)

**Comment by FelipeCasas** [comment] 2024-07-22 18:42
> Now I can stable visualize it by deleting collision part in my urdf and generate to my .usd without collisions part ( Because I check your .usd file in this repo other gripper don't have collision)
> 
> But Now my gripper can't close and open normally, I guess is dofs parameters is not right, considering my gripper also has mimic joints how should I factor this in, any tips would be really helpful. Can you give some instruction where I can get the right open and close status dofs data?
> 
> Close status: ![image](https://private-user-images.githubusercontent.com/41980080/350727140-8f31cd10-fe62-4159-bd5d-334df88209dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzEyODQsIm5iZiI6MTcyMTY3MDk4NCwicGF0aCI6Ii80MTk4MDA4MC8zNTA3MjcxNDAtOGYzMWNkMTAtZmU2Mi00MTU5LWJkNWQtMzM0ZGY4ODIwOWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDE3NTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ZjM2MjllOGY5M2ZkNWU5ZGU2YmI2MzYxM2I1YzM4MDgxZWY2ODgzODMyNjc2YTAxMDZhYjIxYmY2NzAwYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EBZv12r5xFeNBBP7jHF1NCGwvG7F5ml-BIQ-Lykd_BU)

For the open positions you must go to your gripper .usd and inspect the joints this way you can set the initial positions when filtering transferred grasps. The close_dir is a mask that specifies which dofs to close in order to perform the grasp and with which dofs to exert force once the grasp is secured so that the object doesn't fall. 

I hope all this information helps! Let us know if other problems arise.

**Comment by kninad** [comment] 2024-07-22 21:51
> > > Also, I generated my own json file using graspit using neuralgrasps-dataset-generation repo and noticed that the json file generated using it does not match the format of the json I downloaded from the dataset folder provided in this repo, are there any modifications I need to make to the json I generated for my robotiq 85 2f gripper?
> > > Thank you so much for your help!
> > 
> > 
> > I guess the only change would in the grasp pose orientation. For isaac sim grasp poses iirc the grasp pose is a 7D vector: `(posn, quat_wxyz)` where the quaternion is in `wxyz` format whereas for the neuralgrasps-dataset-generation, graspit might save it in `(posn, quat_xyzw)` format. So try changing the graspit pose quaternion to `wxyz` format before applying in isaac sim? Perhaps that should at least give you the gripper in correct orientation.
> 
> I noticed there are some other parameters like graspit_dofs, final_dofs and fall time in the graspit_grasps json in your dataset while in my json there is only poses, dofs, quality and contact links (the last two are not in your json) am I doing something wrong/missing something?
> 
> Thank you!

In the shared dataset, the values in the dict are *after* simulating with isaac sim. So we record the fields of interest from isaac simulation (`final_dofs`, `fall_time`). Whereas with the org. graspit generation, only the `pose`, `dofs` and `quality` are of interest (you can safely ignore `contact_links`). The json from graspit is actually read by our isaacsim testing script [here!](https://github.com/IRVLUTD/isaac_sim_grasping/blob/6a6132db836111f43c8e4df3f49bf9a28969691b/managers.py#L32)

**Comment by Huangruopeng** [comment] 2024-07-22 23:33
> Hello, I was able to replicate your error. It seems that your gripper .usd is not functioning with the PhysiX software. I would recommend to use Isaac Sim GUI to change the .usd of your gripper to a working version. You can use our gripper .usd's as reference.
> 
> ![Screenshot from 2024-07-22 13-33-21](https://private-user-images.githubusercontent.com/31459466/351073094-a03ac847-1ec4-4846-9884-44241025e2e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODUzOTcsIm5iZiI6MTcyMTY4NTA5NywicGF0aCI6Ii8zMTQ1OTQ2Ni8zNTEwNzMwOTQtYTAzYWM4NDctMWVjNC00ODQ2LTk4ODQtNDQyNDEwMjVlMmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDIxNTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZjhjMGI0OGZmZjFiYTJkNmMzYTgzZDJkMjQ2ZjZlNTNhNDFkYzQ2OGNlNTNkMzE0NjhmMmY5ZTk0N2NjZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LRJiJ2rjo6n0P8yhYGeZeQN0QHJH9bwKYVAoa7ClzkA)
> 
> You should be able to manually change the joint positions through the GUI without generating PhysiX errors. An example is below:
> 
> ![Screenshot from 2024-07-22 13-38-31](https://private-user-images.githubusercontent.com/31459466/351074332-08c19706-be8a-4f06-a323-90b9e6e202f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODUzOTcsIm5iZiI6MTcyMTY4NTA5NywicGF0aCI6Ii8zMTQ1OTQ2Ni8zNTEwNzQzMzItMDhjMTk3MDYtYmU4YS00ZjA2LWEzMjMtOTBiOWU2ZTIwMmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDIxNTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MGFlOTkwYjZiOTMwNTJjMzEzN2ZkMTdkYzQzNWU3MjNiNTg0NjE0ZWQwN2ZkMzYxNmY0ZDA1YTQwNzgzYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qQZ5rcbBN8Hf6MW2Eq8LiM9PxNlaZlygca0-S9tY2PU) ![Screenshot from 2024-07-22 13-37-30](https://private-user-images.githubusercontent.com/31459466/351074334-c804b951-96e3-41bf-a8cb-59cfea5e11b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODUzOTcsIm5iZiI6MTcyMTY4NTA5NywicGF0aCI6Ii8zMTQ1OTQ2Ni8zNTEwNzQzMzQtYzgwNGI5NTEtOTZlMy00MWJmLWE4Y2ItNTljZmVhNWUxMWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDIxNTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYmE1MzYwNGZhNzY2ZGM1YzI4YmJiMTRjNDhkNzQzODFhYTZiNzFhODVmZjI3ZWU1ZTU4ZTVkY2FiMzFiZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CNbb8Jr14glewWQIDLPtEySDClwSp2cdiVCF6e3TvPA)

Thank you for your advice!
But Now if I modify the .usd file. the instansbale.usd file will be unmatched. So can I generate instansable.usd file from .usd file?

Thank you so much!

**Comment by FelipeCasas** [comment] 2024-07-23 17:18
> But Now if I modify the .usd file. the instansbale.usd file will be unmatched. So can I generate instansable.usd file from .usd file?

The instanceable meshes were used to reduce the memory usage of the simulation when running many workstations and many standalones in parallel. If you would like to use them, you will need to modify both .usd files, else you can import the gripper without the "Create Instanceable Asset" option and modify that one.

**Comment by Huangruopeng** [comment] 2024-07-23 22:08
> > But Now if I modify the .usd file. the instansbale.usd file will be unmatched. So can I generate instansable.usd file from .usd file?
> 
> The instanceable meshes were used to reduce the memory usage of the simulation when running many grippers and many standalones in parallel. If you would like to use them you will need to modify both .usd files, else you can import the gripper without the "Create Instanceable Asset" option and modify that one.

Thank you for your help.
I try to modify my .usd file and use this link: https://docs.omniverse.nvidia.com/isaacsim/latest/isaac_lab_tutorials/tutorial_instanceable_assets.html
to generate my instanceable.usd file following the h5_hand example structure.
![image](https://github.com/user-attachments/assets/6cbc8fe0-1ffb-4349-a80f-70f09fb11073)
Now it can close and open in usd file as expected.

But now when I run this command:
![image](https://github.com/user-attachments/assets/b0daf9e5-e930-4553-9f50-e662a3589fbd)
I meet this problem:
![image](https://github.com/user-attachments/assets/84fa9217-264c-46da-a3a6-a30e972e8f9a)

I try to set articulation in my usd file.
It is really new to me. Thank you for your patient and help!
Bests,

**Comment by Huangruopeng** [comment] 2024-07-25 22:29
Thank you for your reply!

Now I have add my robotiq 85 gripper, and it can close and open normally. 
But When I run this :
./python.sh /home/lm-2023/Isaac_Sim/grasping/isaac_sim_grasping/standalone.py --json_dir=/home/lm-2023/Isaac_Sim/grasping/Dataset/graspit_grasps/robotiq --gripper_dir=/home/lm-2023/Isaac_Sim/grasping/isaac_sim_grasping/grippers --objects_dir=/home/lm-2023/Isaac_Sim/grasping/Dataset/google_objects_usd --output_dir=/home/lm-2023/Isaac_Sim/grasping/ --num_w=2 --test_time=3 --controller=position --print_results --/log/level=error --/log/fileLogLevel=error --/log/outputStreamLevel=error

The object and gripper can't contact each other with collision. And the object can't drop.
![Screenshot from 2024-07-25 15-24-48](https://github.com/user-attachments/assets/ae51326e-2bc9-4a27-bfd8-a2f37a288700)

So where I need to modify? .usd file or some scripts?

Thank you so much!

**Comment by Huangruopeng** [comment] 2024-07-26 00:34
Hi
I also try h5_hand example, and set over-bound joint data. It also shows overlap. 
![image](https://github.com/user-attachments/assets/81bf380a-a8ea-434a-97e6-ea2119158e3c)
So, if I need to modify some code?
Thank you so much!

**Comment by kninad** [comment] 2024-07-26 17:25
@FelipeCasas maybe its an issue with the collision meshes in the usd?

**Comment by FelipeCasas** [comment] 2024-07-26 18:10
Hello, it's nice to know you were able to fix your problem with controlling the robot!

Our own gripper .usds can be misleading, as in the h5_hand, some only have a visuals frame with the mesh. If you inspect the properties on the visuals you will find a collider property within it. Make sure that your gripper has the colliders set up for the meshes that make it up. 


> I also try h5_hand example, and set over-bound joint data. It also shows overlap.
> ![image](https://private-user-images.githubusercontent.com/41980080/352328088-81bf380a-a8ea-434a-97e6-ea2119158e3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMTYyNzYsIm5iZiI6MTcyMjAxNTk3NiwicGF0aCI6Ii80MTk4MDA4MC8zNTIzMjgwODgtODFiZjM4MGEtYThlYS00MzRhLTk3ZTYtZWEyMTE5MTU4ZTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE3NDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMzhmMzNlMjExMmViZmMyOTJmZjJiYTZkZDU5ZjM0ZWIyZTA4ZjlhYzdlYTlmNmQ5YTRjMTE5NjYyM2EzZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GMNpE83i7Sc3YBzjTTTEaR6Fj420CHAv55t_CcQvm-Q)

Some grippers also have self-collision turned off, you can make them overlap provided the correct joint positions. You would likely need to set this up with your gripper; if it is turned on, the physics simulator will try to process the collisions between your gripper links and unexpected behavior may rise when loading or moving your gripper.

**Closed as completed** 2024-08-02 21:42 UTC
